default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV.fetch("DB_PORT", 3306) %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: <%= ENV["DB_NAME"] %>

test:
  <<: *default
  database: <%= ENV["DB_NAME"] %>_test

production:
  <<: *default
  database: <%= ENV["DB_NAME"] %>
